### ISSUE TITLE
doesn't do local testing unless defined in capabilities

### ISSUE THREAD

**Issue by klamping** [itszero/wdio-browserstack-service#3]
I was able to get this working with my browserstack account, but need to add the `browserstack.local` capability in order for local testing to be enabled:

```
    capabilities: [{
        browserName: 'chrome',
        'browserstack.local': true
    }],
```

I think this should either be automatically added to the caps via the plugin, or documented in the README. I don't mind trying to do either via a PR, but wanted to run it by you first. 

Great work on this by the way. Aside from this issue, it works great!

**Comment by jamesaspence** [comment]
Likewise having issues with this. [Webdriver.io docs](http://webdriver.io/guide/services/browserstack.html#browserstackLocal) for this package say you can set `browserstackLocal` to true in the wdio config. However, doing that did not work - instead, I had to do the same as OP, and spin up my own local BrowserStackLocal service, in order to have my tests successfully run.

**Comment by itszero** [comment]
IIRC It was not possible to change the capabilities from the plugin, thus we cannot inject `browserstack.local` to the capabilities object.

@jamesaspence This plugin should spin up the tunnel service for you, but you will need to set both `browserstackLocal` and this capability to true. Can you confirm if this is the case?

**Comment by jamesaspence** [comment]
@itszero yes, that's the case. I set both of those to true, and was able to run my tests via browserstack. I just wish the docs better explained that this was necessary, as I spent at least an hour scratching my head on this.
